definitions:
  service.createUserInfo:
    properties:
      password:
        type: string
      rePassword:
        type: string
      username:
        type: string
    type: object
  service.loginUserInfo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  service.updateUserInfo:
    properties:
      data:
        type: string
      parameter:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: Welcome!
          schema:
            type: string
      tags:
      - Index
  /user/createUser:
    post:
      parameters:
      - description: username, password, repassword
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.createUserInfo'
      responses:
        "201":
          description: Create user success!
          schema:
            type: string
        "400":
          description: Passwords not same
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: CreateUser
      tags:
      - User
  /user/deleteUser:
    delete:
      parameters:
      - description: username, password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.loginUserInfo'
      responses:
        "204":
          description: Delete user success!
        "400":
          description: Invalid input
          schema:
            type: string
        "401":
          description: Invalid username or password
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: DeleteUser
      tags:
      - User
  /user/getUser:
    post:
      parameters:
      - description: username, password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.loginUserInfo'
      responses:
        "200":
          description: Get user
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "401":
          description: Invalid username or password
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: GetUser by username and password
      tags:
      - User
  /user/getUserList:
    get:
      responses:
        "200":
          description: Get user list
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: GetUserList
      tags:
      - User
  /user/updateUser:
    put:
      parameters:
      - description: username, password, password/telephone/email, data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.updateUserInfo'
      responses:
        "204":
          description: Update user success!
        "400":
          description: Invalid parameter
          schema:
            type: string
        "401":
          description: Invalid username or password
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: UpdateUser
      tags:
      - User
swagger: "2.0"
