definitions:
  service.userInfo:
    properties:
      password:
        type: string
      repassword:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: Welcome!
          schema:
            type: string
      tags:
      - Index
  /user/createUser:
    post:
      parameters:
      - description: username, password, repassword
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.userInfo'
      responses:
        "201":
          description: Create user success!
          schema:
            type: string
        "400":
          description: Passwords do not match
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: CreateUser
      tags:
      - User
  /user/deleteUser:
    delete:
      parameters:
      - description: username, password, any
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.userInfo'
      responses:
        "204":
          description: Delete user success!
      summary: DeleteUser
      tags:
      - User
  /user/getUserList:
    get:
      responses:
        "200":
          description: Get user list
          schema:
            type: string
      summary: GetUserList
      tags:
      - User
  /user/updateUser:
    put:
      parameters:
      - description: username, old password, new password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.userInfo'
      responses:
        "204":
          description: Update user success!
      summary: UpdateUser
      tags:
      - User
swagger: "2.0"
